import { Inter } from "next/font/google";
import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";
import { useRecoilState, useRecoilValue } from "recoil";
import { isOpenMenuState } from "@/state/isOpenMenuState";
import { isShowContactPopupState } from "@/state/isShowContactPopupState";
import { useEffect } from "react";
import ContactForm from "./ContactForm";

const inter = Inter({ subsets: ["latin"] });

interface MainLayoutProps {
    children: React.ReactNode;
}

function MainLayout({ children }: MainLayoutProps) {
    const [isOpenMenu, setIsOpenMenu] = useRecoilState(isOpenMenuState);
    const isShowContactPopup = useRecoilValue(isShowContactPopupState);

    useEffect(() => {
        const handleResize = () => {
            if (window.innerWidth >= 640) {
                setIsOpenMenu(false);
            }
        };

        // Initial check
        handleResize();

        // Listen for resize events
        window.addEventListener("resize", handleResize);

        // Clean up event listener on component unmount
        return () => {
            window.removeEventListener("resize", handleResize);
        };
    }, []);

    return (
        <div
            className={`${inter.className} ${
                isShowContactPopup ? "" : ""
            } text-gray-700`}
        >
            {/* Meta tags */}
            <Head>
                <title>Sambath Soth</title>
                <meta name="description" content="Generated by Sambath Soth" />
                <link rel="icon" href="/favicon.svg" />
            </Head>

            <div>
                {/* Header */}
                <Header />

                {!isOpenMenu ? (
                    <div>
                        {/* Main Content */}
                        <main>{children}</main>

                        {/* Footer */}
                        <Footer />
                    </div>
                ) : null}
            </div>

            {/* Contact Popup */}
            <ContactForm />
        </div>
    );
}

export default MainLayout;
